### ISSUE TITLE
Please add typescript support

### ISSUE THREAD

**Issue by Cybermb** [jybleau/parseable-winston#1]
Please add typescript support

**Comment by jybleau** [comment]
Never used TS before. I'll look on how to add basic support.

**Comment by jybleau** [comment]
I've added basic typescript support in release v0.2.0.
Also published on NPM.
Tell me if it works for you, thanks.

**Comment by Cybermb** [comment]
Your engine requirement is too strict
https://github.com/jybleau/parseable-winston/blob/de897f8014939424f3b571e2e1068764d09e08db/package.json#L38
I can't even install package now
```
The engine "yarn" is incompatible with this module. Expected version "^1.22.19". Got "1.22.10"
The engine "node" is incompatible with this module. Expected version "^18.17.1". Got "20.11.0"
```

I don't think that you need to specify engines at all...

**Comment by jybleau** [comment]
Do you have `engine-strict` enabled? `npm config ls -l | grep engine`
https://docs.npmjs.com/cli/v10/using-npm/config#engine-strict

It's suppose to be just a warning by default. 

Anyway, I got it wrong, I've changed the values and published v0.2.3.

Yes, not needed for TS, I added to indicate minimum supported engine.

Thanks for the feedback.

**Comment by Cybermb** [comment]
Thanks for taking look at this. It seems that basic TS support does allow importing your package into project as a module 🥳
However, I am not able to add `ParseableTransport` as a tranport for winston. 
I am getting this type error:
```
Type 'ParseableTransport' is not assignable to type 'TransportStream'.
  The types returned by 'end(...)' are incompatible between these types.
    Type 'Promise<void>' is missing the following properties from type 'TransportStream': writable, writableEnded, writableFinished, writableHighWaterMark, and 33 more.ts(2322)
```
I am not sure why it complains. It probably works if we ignore type errors

**Comment by jybleau** [comment]
I've published a new version 0.2.4 with more TS code conversion.

There are less build errors but still this one : 
```
Type 'ParseableTransport' is missing the following properties from type 'TransportStream': writable, writableEnded, writableFinished, writableHighWaterMark, and 32 more
```

Not sure how to fix it yet...

It's supposed to be fixed by changing those tsconfig properties: 

```
  "moduleResolution": "node",
  "esModuleInterop": true
```

Still, it does compile and run correctly. I'll have a look at how LogTailTransport has been done...


NB: module import should be done like this:

```
import { ParseableTransport } from 'parseable-winston';

or

const { ParseableTransport }  require('parseable-winston');
```

**Comment by Cybermb** [comment]
Removing `async` and `await` from `end()` method seem to fix this error:
 `Type 'ParseableTransport' is missing the following properties from type 'TransportStream': writable, writableEnded, writableFinished, writableHighWaterMark, and 32 more`
But after that you will get a new  error here:
`super.end(args, () => {})`
`Property 'end' does not exist on type 'TransportStream'`
Did you mean to use `super.close()` instead?

**Comment by jybleau** [comment]
I've rewritten the way the close call is handled; removed `async` and use an `onClose` method instead. 
Anyway, when `TransportStream` call its `close` property there is no async or callback support, so it's useless await for the buffer to flush on logger close.

I can build with no error using version 0.3.0.

Thanks again.

**Comment by Cybermb** [comment]
Thanks! It seems to be working now
